apps/belt/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^main/$', views.main, name='main'),
    url(r'^process/$', views.process, name='process'),
    url(r'^login/$', views.login, name='login'),
    url(r'^travels/$', views.traveldash, name='travels'),
    url(r'^travels/add/$', views.add, name='add'),
    url(r'^travels/verify/$', views.verify, name='verify'),
    url(r'^travels/destination/(?P<id>\d+)/$', views.destination, name='destination'),
    url(r'^travels/join/(?P<id>\d+)/$', views.join, name='join'),
    url(r'^logout/$', views.logout, name='logout'),
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.belt.urls', namespace='tbuddy'))
]

apps/belt/models.py
from __future__ import unicode_literals

from django.db import models
import bcrypt
from datetime import datetime

# Create your models here.

class TripManager(models.Manager):
    def validate(self,data,user):
        errors = []
        if len(data['destination']) < 1:
            errors.append("Please enter a destination")

        if len(data['plan']) < 1:
            errors.append("Please enter a plan")

        if len(data['start']) < 1:
            errors.append("Please enter a start date!")
        elif datetime.strptime(data['start'], '%Y-%m-%d') < datetime.today():
            errors.append("Travel start date cannot be in the past")

        if len(data['end']) < 1:
            errors.append("Please enter an end date!")
        elif datetime.strptime(data['end'], '%Y-%m-%d') < datetime.strptime(data['start'], '%Y-%m-%d'):
            errors.append("Your trip cannot end before it starts!")

        if len(errors) == 0:
            trip = self.create(destination=data['destination'], plan=data['plan'], start=data['start'], end=data['end'], host=user)
            return trip.id

        return errors

class UserManager(models.Manager):
    def registration(self, data):
        errors =[]
        if len(data['name']) < 3:
            errors.append('Name must contain atleast 3 characters')
        if len(data['username']) < 3:
            errors.append('Username must contain atleast 3 characters')
        if len(data['password']) < 8:
            errors.append('Password must be greater than 8 characters')
        check_username = self.filter(username=data['username'])
        if check_username:
            errors.append('Username has already been taken')
        if data['password'] != data['confirm_password']:
            errors.append('Password and password confirmation fields did not match')
        if len(errors) == 0:
            user = self.create(name=data['name'], username=data['username'], password=bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt()))
            return user.id
        return errors

    def verify_login(self, data):
        errors = []
        if len(data['password']) == 0:
            errors.append('Please enter your password')
        check_user = User.objects.filter(username = data['username'])
        if check_user:
            hashed_pw = bcrypt.hashpw(data['password'].encode(), check_user[0].password.encode())
            if check_user[0].password == hashed_pw:
                pass
            else:
                errors.append('Username and Password do not match')
        else:
            errors.append('Username not found')
        return errors

class User(models.Model):
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

class Trip(models.Model):
    destination = models.CharField(max_length=255)
    plan = models.TextField()
    start = models.DateField()
    end = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    host = models.ForeignKey(User, related_name='trip_host', blank=True, null=True)
    trips = models.ManyToManyField(User, related_name='trip_users')
    objects = TripManager()

apps/belt/views.py
from django.shortcuts import render
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import render,redirect
from .models import User, Trip
import bcrypt
from datetime import datetime

# Create your views here.
def main(request):
    return render(request, 'belt/login.html')

def process(request):
    if request.method == 'POST':
        data = request.POST.copy()
        errors = User.objects.registration(data)
        if isinstance(errors, int):
            user = User.objects.get(id=errors)
            request.session['user_id'] = user.id
            request.session['username'] = user.username
            return redirect('/travels')
        for error in errors:
            messages.error(request, error)
    return redirect('/main')

def login(request):
    if request.method == 'POST':
        data = request.POST.copy()
        errors = User.objects.verify_login(data)
        if not errors:
            user = User.objects.get(username=data['username'])
            request.session['user_id'] = user.id
            request.session['username'] = user.username
            return redirect('/travels')
        for error in errors:
            messages.error(request,error)
    return redirect('/main')

def traveldash(request):
    if 'user_id' not in request.session:
        return redirect('/main')
    print request.session['user_id']
    user = User.objects.get(id=request.session['user_id'])
    context = {
        'my_trips': Trip.objects.filter(host=user)|Trip.objects.filter(trips=user),
        'other_trips': Trip.objects.exclude(host=user).exclude(trips=user)
    }
    return render(request, 'belt/travels.html', context)


def add(request):
    if 'user_id' not in request.session:
        return redirect('/main')
    return render(request, 'belt/add.html')


def verify(request):
    data = request.POST.copy()
    user = User.objects.get(id=request.session['user_id'])
    result = Trip.objects.validate(data, user)
    if isinstance(result, list):
        for error in result:
            messages.error(request, error)
    if isinstance(result,int):
        messages.success(request,"Succesfully Added Trip!")
        return redirect('/travels/')
    return redirect(reverse('tbuddy:add'))


def destination(request, id):
    if 'user_id' not in request.session:
        return redirect('/main')
    context= {
        'trip': Trip.objects.get(id=id),
        'other_users': User.objects.filter(trip_users__id=id)
    }
    return render(request, 'belt/destination.html', context)

def join(request,id):
    user = User.objects.get(id=request.session['user_id'])
    trip = Trip.objects.get(id=id)
    trip.trips.add(user)
    return redirect('/travels')

def logout(request):
    request.session.clear()
    return redirect('/main')

apps/belt/templates/belt/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Plan</title>
    <style media="screen">
        .error{
            color:red;
        }
        .success{
            color:green;
        }
    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">
</head>
<body>
     {% if messages %}
        <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    <h1>Add a Trip!</h1>
    <p><span><a href="{% url 'tbuddy:travels' %}">Home</a> <a href="{% url 'tbuddy:logout' %}">Logout</a></span></p>
    <br>
    <form action="{% url 'tbuddy:verify' %}" method='POST' class='container'>
        {% csrf_token %}
        <label for="">
            Destination: <p><input type="text" name='destination'></p>
        </label>
        <label for="">
            Plan: <p><input type="text" name='plan'></p>
        </label>
        <label for="">
            Travel Start Date: <p><input type="date" name='start'></p>
        </label>
        <label for="">
            Travel End Date: <p><input type="date" name='end'></p>
        </label>
        <input type="Submit">
    </form>
</body>
</html>

apps/belt/templates/belt/destination.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Destination</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">
    </head>
    <body>
        <h1>{{trip.destination}}</h1>
        <p>Planned By: {{trip.host.name}}</p>
        <p>Description: {{trip.plan}}</p>
        <p>Travel Start: {{trip.start}}</p>
        <p>Travel End: {{trip.end}}</p>

        <h3>Other users joining:</h3>
        {% for user in other_users%}
            <p>{{user.name}}</p>
        {% endfor %}


    </body>
</html>

apps/belt/templates/belt/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Login and Registration</title>
        <style media="screen">
            .error{
                color:red;
            }
            .success{
                color:green;
            }
        </style>
    </head>
    <body>
        {% if messages %}
        <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
        {% endif %}
        <fieldset>
            <legend>Registration</legend>
            <form action="/process/" method="post">
                {% csrf_token %}
                <label>
                    <p>First Name: <input type="text" name="first_name"></p>
                </label>
                <label>
                    <p>Last Name: <input type="text" name="last_name"></p>
                </label>
                <label>
                    <p>Email: <input type="text" name="email"></p>
                </label>
                <label>
                    <p>Password: <input type="text" name="password"></p>
                </label>
                <label>
                    <p>Confirm Password: <input type="text" name="confirm_password"></p>
                </label>
                <br>
                <input type="submit" value="Register">
            </form>
        </fieldset>
        <fieldset>
            <legend>Login</legend>
            <form action="/login/" method="post">
                {% csrf_token %}
                <label>
                    <p>Email: <input type="text" name="email"></p>
                </label>
                <label>
                    <p>Password: <input type="text" name="password"></p>
                </label>
                <br>
                <input type="Submit" value="Login">
            </form>
        </fieldset>
    </body>
</html>

apps/belt/templates/belt/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Login and Registration</title>
        <style media="screen">
            .error{
                color:red;
            }
            .success{
                color:green;
            }
        </style>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">
    </head>
    <body>
        {% if messages %}
        <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
        {% endif %}
        <fieldset class='container'>
            <legend>Registration</legend>
            <form action="/process/" method="post" class='container'>
                {% csrf_token %}
                <label>
                    <p>Name: <input type="text" name="name"></p>
                </label>
                <label>
                    <p>Username: <input type="text" name="username"></p>
                </label>
                <label>
                    <p>Password: <input type="password" name="password"></p>
                </label>
                <p>* Password must be atleast 8 characters!</p>
                <label>
                    <p>Confirm Password: <input type="password" name="confirm_password"></p>
                </label>
                <br>
                <input type="submit" value="Register">
            </form>
        </fieldset>
        <fieldset class='container'>
            <legend>Login</legend>
            <form action="/login/" method="post" class='container'>
                {% csrf_token %}
                <label>
                    <p>Username: <input type="text" name="username"></p>
                </label>
                <label>
                    <p>Password: <input type="password" name="password"></p>
                </label>
                <br>
                <input type="Submit" value="Login">
            </form>
        </fieldset>
    </body>
</html>

apps/belt/templates/belt/travels.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Travel Dashboard</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">
    <style media="screen">
        .error{
            color:red;
        }
        .success{
            color:green;
        }
    </style>

</head>
<body>
    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
    {% endif %}
    <h1> Hello, {{request.session.username}}!</h1>
    <P><a href="{% url 'tbuddy:logout' %}">Logout</a></P>
    <h3> Your Trip Schedules: </h3>
        <table class="container centered" >
            <thead>
                <tr>
                  <th>Destination</th>
                  <th>Travel Start Date</th>
                  <th>Travel End Date</th>
                  <th>Plan</th>
                </tr>
            </thead>
          <tbody>
              {% for trip in my_trips %}
              <tr>
              <td><a href="{% url 'tbuddy:destination' id=trip.id%}">{{trip.destination}}</a></td>
              <td>{{trip.start}}</td>
              <td>{{trip.end}}</td>
              <td>{{trip.plan}}</td>
              </tr>
              {% endfor %}
          </tbody>
        </table>
    <h3> Other User's Trip Schedules: </h3>
        <table class="container centered">
        <thead>
        <tr>
            <th>Name</th>
            <th>Destination</th>
            <th>Travel Start Date</th>
            <th>Travel End Date</th>
            <th>Plan</th>
            <th>Interested?</th>
        </tr>
        </thead>
        <tbody>
            {% for trip in other_trips%}
            <tr>
            <td>{{trip.host.name}}</td>
            <td>{{trip.destination}}</td>
            <td>{{trip.start}}</td>
            <td>{{trip.end}}</td>
            <td>{{trip.plan}}</td>
            <td><a href="{% url 'tbuddy:join' id=trip.id%}">Join</a></td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
    <a href="{% url 'tbuddy:add' %}">Add Travel Plan</a>
</body>
</html>